version: '3.8'

services:
  lafoncedalleapi:
    build:
      context: .
      dockerfile: api.Dockerfile # Utilise le Dockerfile de l'API
    container_name: lafoncedalleapi
    command: gunicorn --workers 4 --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app # On peut garder le bind mount ici pour le développement
    env_file:
      - .env
    networks:
      - lafoncedallenet
    restart: unless-stopped

  lafoncedallebot:
    build:
      context: .
      dockerfile: bot.Dockerfile # Utilise le Dockerfile du bot
      args: # On passe les arguments pour le clonage
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
        - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
    container_name: lafoncedallebot
    # Le 'command' est maintenant dans le Dockerfile, donc plus besoin ici
    volumes:
      # !! CORRECTION CRUCIALE !!
      - ./bot_state.json:/app/bot_state.json
      - ./ratings.db:/app/ratings.db
    env_file:
      - .env
    depends_on:
      - lafoncedalleapi
    networks:
      - lafoncedallenet
    restart: unless-stopped

networks:
  lafoncedallenet:
    driver: bridge