version: '3.8'

services:
  # Service de l'API Flask
  lafoncedalleapi:
    build: .
    container_name: lafoncedalleapi
    restart: always
    command: ["python", "app.py"]
    env_file:
      - .env
    volumes:
      - ./ratings.db:/app/ratings.db
      - ./bot_state.json:/app/bot_state.json
      - ./welcome_codes.txt:/app/welcome_codes.txt
      - ./claimed_welcome_codes.json:/app/claimed_welcome_codes.json
      - ./nitro_codes.txt:/app/nitro_codes.txt
      - ./claimed_nitro_codes.json:/app/claimed_nitro_codes.json
      - ./scrape_cache.json:/app/scrape_cache.json
      - ./user_actions.log:/app/user_actions.log
    networks:
      - lafoncedallenet

  # Service du Bot Discord
  lafoncedallebot:
    build: .
    container_name: lafoncedallebot
    restart: always
    depends_on:
      - lafoncedalleapi
    env_file:
      - .env
    volumes:
      - ./ratings.db:/app/ratings.db
      - ./bot_state.json:/app/bot_state.json
      - ./welcome_codes.txt:/app/welcome_codes.txt
      - ./claimed_welcome_codes.json:/app/claimed_welcome_codes.json
      - ./nitro_codes.txt:/app/nitro_codes.txt
      - ./claimed_nitro_codes.json:/app/claimed_nitro_codes.json
      - ./scrape_cache.json:/app/scrape_cache.json
      - ./user_actions.log:/app/user_actions.log
    networks:
      - lafoncedallenet

# Définition du réseau partagé
networks:
  lafoncedallenet:
    driver: bridge