version: '3.8'

services:
  lafoncedalleapi:
    build: .
    container_name: lafoncedalleapi
    command: gunicorn --workers 4 --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - lafoncedallenet # <-- Doit être présent
    restart: unless-stopped

  lafoncedallebot:
    build: .
    container_name: lafoncedallebot
    command: python bot_runner.py # Ou votre script start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on: # <-- Important pour l'ordre de démarrage
      - lafoncedalleapi
    networks:
      - lafoncedallenet # <-- Doit être présent
    restart: unless-stopped

networks: # <-- Cette section est OBLIGATOIRE
  lafoncedallenet:
    driver: bridge